#!/bin/sh
# Copyright 2020, 2025 Michael Reilly (mreilly@mreilly.dev).
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the names of the copyright holders nor the names of the
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# See README for usage discussion

set -e

if [ ! -n "$HEXPEEK_BASEDIR" ]; then
    export HEXPEEK_BASEDIR=$(cd .. ; pwd -P)
fi

. "$HEXPEEK_BASEDIR/test/shcommon"

rm -rf $Results
mkdir -p $Results
Logfile="$Results/run.log"

printf "$PgmName test log, start: %s\n" $(date -Iseconds) > $Logfile
logsep 2>> $Logfile

Suite="all"
if [ -n "$1" ]; then
    Suite="$1"
    shift
fi

echo "Running $PgmName $Suite tests"

if [ "$Suite" = "all" ]; then
    "$HEXPEEK_BASEDIR"/test/base/local $* 2>> $Logfile
    "$HEXPEEK_BASEDIR"/test/advanced/local $* 2>> $Logfile
    "$HEXPEEK_BASEDIR"/test/advanced/local -plugins $* 2>> $Logfile
    "$HEXPEEK_BASEDIR"/test/fixedxl/local $* 2>> $Logfile
else
    if [ ! -f "$HEXPEEK_BASEDIR"/test/"$Suite"/local ]; then
        printf "%s is not a test suite!\n" "$Suite"
        exit 2
    fi
    "$HEXPEEK_BASEDIR"/test/"$Suite"/local $* 2>> $Logfile
fi

echo "$PgmName $Suite test script completed successfully"
exit 0
