#!/bin/sh
# Copyright 2020, 2025 Michael Reilly (mreilly@mreilly.dev).
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the names of the copyright holders nor the names of the
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

HEXPEEK_TESTLEVEL="base"
. "$HEXPEEK_BASEDIR/test/shcommon"

cp $Datasrc/*data $Datasrc/*.in $Results

$Testbin/exampletest 0 1 $*
$Testbin/exampletest 1 1 $*
$Testbin/exampletest 2 1 $*
$Testbin/exampletest 3 1 $*
$Testbin/exampletest 4 1 $*
$Testbin/exampletest 10 1 $*
$Testbin/exampletest 20 2 $*
$Testbin/exampletest 30 1 $*
$Testbin/exampletest 31 1 $*
$Testbin/exampletest 32 1 $*
$Testbin/exampletest 33 1 $*
$Testbin/exampletest 34 1 $*
$Testbin/exampletest 40 1 $*
$Testbin/exampletest 41 1 $*
$Testbin/exampletest 42 1 $*
$Testbin/exampletest 50 1 $*
$Testbin/exampletest 51 1 $*
$Testbin/exampletest 52 1 $*

$Testbin/basictest 0 1 $*
$Testbin/basictest 1 1 $*
$Testbin/basictest 2 1 $*
$Testbin/basictest 3 1 $*
$Testbin/basictest 4 1 $*
$Testbin/basictest 5 1 $*
$Testbin/basictest 6 2 $*
$Testbin/basictest 7 2 $*

$Testbin/basictest 11 1 $*
$Testbin/basictest 13 1 $*
$Testbin/basictest 14 1 $*
$Testbin/basictest 15 1 $*
$Testbin/basictest 17 2 $*

$Testbin/endianltest $*
$Testbin/sparsetest $*

$Testbin/flagtests $*

$Testbin/difftest $*
$Testbin/packtest $*
$Testbin/rectest $*

$Testbin/redirecttest $*
$Testbin/pipetest $*
$Testbin/fdrectest $*
$Testbin/sockettest $*

exit 0
